<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/data.php';

coolopz_require_login();

function coolopz_build_job_form_from_record(array $job, array $servicePriceMap): array
{
    $jobForm = [
        'ticket_number' => $job['ticket_number'],
        'customer_name' => $job['customer_name'],
        'service_lines' => coolopz_fetch_job_service_lines((int) $job['id']),
        'technician_team' => $job['technician_team'],
        'attending_technicians' => coolopz_parse_summary_names($job['attending_technicians'] ?? ''),
        'site_address' => $job['site_address'] ?? '',
        'google_maps_url' => $job['google_maps_url'] ?? '',
        'person_in_charge_name' => $job['person_in_charge_name'] ?? '',
        'person_in_charge_contact' => $job['person_in_charge_contact'] ?? '',
        'client_update_token' => $job['client_update_token'] ?? '',
        'status' => $job['status'],
        'priority_level' => $job['priority_level'],
        'billed_amount' => '0.00',
        'notes' => $job['notes'],
    ];

    if ($jobForm['service_lines'] === [] && $job['service_type'] !== '') {
        $fallbackLines = [];
        foreach (coolopz_normalize_service_names(explode(',', (string) $job['service_type'])) as $serviceName) {
            $fallbackLines[] = [
                'service_name' => $serviceName,
                'line_price' => $servicePriceMap[$serviceName] ?? 0,
            ];
        }

        $jobForm['service_lines'] = $fallbackLines;
    }

    $jobForm['billed_amount'] = number_format(coolopz_calculate_billed_amount($jobForm['service_lines']), 2, '.', '');

    return $jobForm;
}

function coolopz_uploaded_file_from_index(array $fileField, int|string $index): ?array
{
    if (!isset($fileField['error'][$index])) {
        return null;
    }

    return [
        'name' => $fileField['name'][$index] ?? '',
        'type' => $fileField['type'][$index] ?? '',
        'tmp_name' => $fileField['tmp_name'][$index] ?? '',
        'error' => $fileField['error'][$index] ?? UPLOAD_ERR_NO_FILE,
        'size' => $fileField['size'][$index] ?? 0,
    ];
}

$currentUser = coolopz_current_user();
$pageTitle = 'CoolOpz Portal | Jobs';
$activePage = 'jobs';
$currentUserName = $currentUser['name'] ?? 'Admin User';
$currentUserRole = $currentUser['role'] ?? 'Operations Admin';
$userInitials = coolopz_user_initials($currentUserName);

$services = coolopz_fetch_services();
$servicePriceMap = [];
foreach ($services as $service) {
    $servicePriceMap[(string) $service['name']] = (float) $service['default_price'];
}
$serviceTypes = array_map(static fn (array $service): string => $service['name'], $services);
$defaultServiceType = $serviceTypes[0] ?? '';
$statuses = coolopz_job_statuses();
$priorities = coolopz_job_priorities();
$customerOptions = coolopz_fetch_customer_options();
$staffTechnicians = coolopz_fetch_assignable_staff();
$staffTechnicianNames = array_map(static fn (array $staffUser): string => $staffUser['full_name'], $staffTechnicians);

$errorMessage = '';
$messageKey = (string) ($_GET['message'] ?? '');
$successMessage = match ($messageKey) {
    'created' => 'Job created successfully.',
    'updated' => 'Job updated successfully.',
    'deleted' => 'Job deleted successfully.',
    'link-regenerated' => 'Client update link regenerated successfully.',
    'photos-updated' => 'Report photos uploaded successfully.',
    default => '',
};
$shouldOpenJobModal = false;
$autoGeneratedTicketNumber = coolopz_generate_job_ticket_number();
$reportUploadJobId = 0;
$jobReportPhotoMap = [
    'services' => [],
    'gas_meter' => [
        'before' => null,
        'after' => null,
    ],
];

$jobForm = [
    'ticket_number' => $autoGeneratedTicketNumber,
    'customer_name' => '',
    'service_lines' => $defaultServiceType !== '' ? [[
        'service_name' => $defaultServiceType,
        'line_price' => $servicePriceMap[$defaultServiceType] ?? 0,
    ]] : [],
    'technician_team' => '',
    'attending_technicians' => [],
    'site_address' => '',
    'google_maps_url' => '',
    'person_in_charge_name' => '',
    'person_in_charge_contact' => '',
    'client_update_token' => '',
    'status' => 'Queued',
    'priority_level' => 'Medium',
    'billed_amount' => $defaultServiceType !== '' ? number_format(coolopz_calculate_billed_amount([[
        'service_name' => $defaultServiceType,
        'line_price' => $servicePriceMap[$defaultServiceType] ?? 0,
    ]]), 2, '.', '') : '0.00',
    'notes' => '',
];

$prefillCustomerId = isset($_GET['customer_id']) ? (int) $_GET['customer_id'] : 0;
$editJobId = isset($_GET['edit']) ? (int) $_GET['edit'] : 0;

if ($_SERVER['REQUEST_METHOD'] !== 'POST' && $editJobId === 0 && $prefillCustomerId > 0) {
    $prefillCustomer = coolopz_find_customer($prefillCustomerId);

    if ($prefillCustomer !== null) {
        $jobForm['customer_name'] = (string) ($prefillCustomer['name'] ?? '');
        $shouldOpenJobModal = true;
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = (string) ($_POST['action'] ?? 'create');

    if ($action === 'upload_report_photos') {
        $uploadJobId = (int) ($_POST['job_id'] ?? 0);
        $existingJob = $uploadJobId > 0 ? coolopz_find_job($uploadJobId) : null;

        if ($uploadJobId < 1 || $existingJob === null) {
            $errorMessage = 'The selected job could not be found.';
        } else {
            $editJobId = $uploadJobId;
            $reportUploadJobId = $uploadJobId;
            $shouldOpenJobModal = true;
            $jobForm = coolopz_build_job_form_from_record($existingJob, $servicePriceMap);

            try {
                $uploadedCount = 0;
                $serviceReportKeys = (array) ($_POST['service_report_keys'] ?? []);

                foreach ($serviceReportKeys as $index => $serviceName) {
                    $normalizedServiceName = trim((string) $serviceName);
                    if ($normalizedServiceName === '') {
                        continue;
                    }

                    $beforePhoto = coolopz_uploaded_file_from_index((array) ($_FILES['service_before'] ?? []), $index);
                    $afterPhoto = coolopz_uploaded_file_from_index((array) ($_FILES['service_after'] ?? []), $index);

                    if ($beforePhoto !== null && (int) ($beforePhoto['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_NO_FILE) {
                        coolopz_store_job_report_photo($uploadJobId, $normalizedServiceName, 'service_before', $beforePhoto, $currentUserName);
                        $uploadedCount++;
                    }

                    if ($afterPhoto !== null && (int) ($afterPhoto['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_NO_FILE) {
                        coolopz_store_job_report_photo($uploadJobId, $normalizedServiceName, 'service_after', $afterPhoto, $currentUserName);
                        $uploadedCount++;
                    }
                }

                $gasMeterBefore = (array) ($_FILES['gas_meter_before'] ?? ['error' => UPLOAD_ERR_NO_FILE]);
                $gasMeterAfter = (array) ($_FILES['gas_meter_after'] ?? ['error' => UPLOAD_ERR_NO_FILE]);

                if ((int) ($gasMeterBefore['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_NO_FILE) {
                    coolopz_store_job_report_photo($uploadJobId, '', 'gas_meter_before', $gasMeterBefore, $currentUserName);
                    $uploadedCount++;
                }

                if ((int) ($gasMeterAfter['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_NO_FILE) {
                    coolopz_store_job_report_photo($uploadJobId, '', 'gas_meter_after', $gasMeterAfter, $currentUserName);
                    $uploadedCount++;
                }

                if ($uploadedCount === 0) {
                    $errorMessage = 'Select at least one photo to upload.';
                } else {
                    header('Location: jobs.php?edit=' . urlencode((string) $uploadJobId) . '&message=photos-updated');
                    exit;
                }
            } catch (RuntimeException $exception) {
                $errorMessage = $exception->getMessage();
            }
        }
    } elseif ($action === 'regenerate_client_link') {
        $regenerateJobId = (int) ($_POST['job_id'] ?? 0);

        if ($regenerateJobId < 1 || coolopz_find_job($regenerateJobId) === null) {
            $errorMessage = 'The selected job could not be found.';
        } else {
            coolopz_regenerate_job_client_update_token($regenerateJobId);
            header('Location: jobs.php?message=link-regenerated');
            exit;
        }
    } elseif ($action === 'delete') {
        $deleteJobId = (int) ($_POST['job_id'] ?? 0);

        if ($deleteJobId < 1 || coolopz_find_job($deleteJobId) === null) {
            $errorMessage = 'The selected job could not be found.';
            $shouldOpenJobModal = false;
        } else {
            coolopz_delete_job($deleteJobId);
            header('Location: jobs.php?message=deleted');
            exit;
        }
    } else {
        $editJobId = $action === 'update' ? (int) ($_POST['job_id'] ?? 0) : 0;
        $existingJob = $action === 'update' && $editJobId > 0 ? coolopz_find_job($editJobId) : null;
        if ($existingJob !== null) {
            $reportUploadJobId = $editJobId;
        }
        $rawPersonInChargeContact = trim((string) ($_POST['person_in_charge_contact'] ?? ''));
        $jobForm = [
            'ticket_number' => $action === 'update' && $existingJob !== null ? $existingJob['ticket_number'] : $autoGeneratedTicketNumber,
            'customer_name' => trim((string) ($_POST['customer_name'] ?? '')),
            'service_lines' => coolopz_normalize_service_lines(
                (array) ($_POST['service_types'] ?? []),
                (array) ($_POST['service_prices'] ?? [])
            ),
            'technician_team' => trim((string) ($_POST['technician_team'] ?? '')),
            'attending_technicians' => coolopz_normalize_technician_names((array) ($_POST['attending_technicians'] ?? [])),
            'site_address' => trim((string) ($_POST['site_address'] ?? '')),
            'google_maps_url' => trim((string) ($_POST['google_maps_url'] ?? '')),
            'person_in_charge_name' => trim((string) ($_POST['person_in_charge_name'] ?? '')),
            'person_in_charge_contact' => coolopz_normalize_phone_number($rawPersonInChargeContact),
            'client_update_token' => trim((string) ($_POST['client_update_token'] ?? '')),
            'status' => trim((string) ($_POST['status'] ?? 'Queued')),
            'priority_level' => trim((string) ($_POST['priority_level'] ?? 'Medium')),
            'billed_amount' => '0.00',
            'notes' => trim((string) ($_POST['notes'] ?? '')),
        ];
        $jobForm['billed_amount'] = number_format(coolopz_calculate_billed_amount($jobForm['service_lines']), 2, '.', '');
        $allowedCustomers = array_map(static fn (array $customer): string => $customer['name'], $customerOptions);
        $allowedTechnicians = array_map(static fn (array $staffUser): string => $staffUser['full_name'], $staffTechnicians);

        if ($action === 'update' && $existingJob !== null && $existingJob['customer_name'] !== '') {
            $allowedCustomers[] = $existingJob['customer_name'];
        }
        $allowedCustomers = array_values(array_unique($allowedCustomers));

        if ($action === 'update' && $existingJob !== null && $existingJob['service_type'] !== '') {
            $serviceTypes = array_merge($serviceTypes, coolopz_normalize_service_names(explode(',', $existingJob['service_type'])));
        }
        $serviceTypes = array_values(array_unique($serviceTypes));

        if ($action === 'update' && $existingJob !== null && $existingJob['technician_team'] !== '') {
            $allowedTechnicians[] = $existingJob['technician_team'];
        }
        if ($action === 'update' && $existingJob !== null && ($existingJob['attending_technicians'] ?? '') !== '') {
            $allowedTechnicians = array_merge($allowedTechnicians, coolopz_parse_summary_names($existingJob['attending_technicians']));
        }
        $allowedTechnicians = array_values(array_unique($allowedTechnicians));

        if ($serviceTypes === []) {
            $errorMessage = 'Add at least one service before creating a job.';
            $shouldOpenJobModal = true;
        } elseif ($jobForm['service_lines'] === []) {
            $errorMessage = 'Add at least one service type to the job.';
            $shouldOpenJobModal = true;
        } elseif ($jobForm['customer_name'] !== '' && !in_array($jobForm['customer_name'], $allowedCustomers, true)) {
            $errorMessage = 'Select a customer from the customer list.';
            $shouldOpenJobModal = true;
        } elseif (array_diff(array_column($jobForm['service_lines'], 'service_name'), $serviceTypes) !== []) {
            $errorMessage = 'Select valid service types from the service list.';
            $shouldOpenJobModal = true;
        } elseif ($jobForm['technician_team'] !== '' && !in_array($jobForm['technician_team'], $allowedTechnicians, true)) {
            $errorMessage = 'Select a lead technician from the staff list.';
            $shouldOpenJobModal = true;
        } elseif (array_diff($jobForm['attending_technicians'], $allowedTechnicians) !== []) {
            $errorMessage = 'Select valid attending technicians from the staff list.';
            $shouldOpenJobModal = true;
        } elseif (!in_array($jobForm['status'], $statuses, true)) {
            $errorMessage = 'Select a valid job status.';
            $shouldOpenJobModal = true;
        } elseif (!in_array($jobForm['priority_level'], $priorities, true)) {
            $errorMessage = 'Select a valid priority level.';
            $shouldOpenJobModal = true;
        } elseif ($jobForm['google_maps_url'] !== '' && filter_var($jobForm['google_maps_url'], FILTER_VALIDATE_URL) === false) {
            $errorMessage = 'Enter a valid Google Maps link.';
            $shouldOpenJobModal = true;
        } elseif (!coolopz_is_valid_phone_number($rawPersonInChargeContact)) {
            $errorMessage = 'Person In Charge contact must be a valid phone number.';
            $shouldOpenJobModal = true;
        } elseif ($action === 'update' && ($editJobId < 1 || $existingJob === null)) {
            $errorMessage = 'The job you are trying to update no longer exists.';
            $shouldOpenJobModal = true;
        } else {
            $jobPayload = $jobForm;
            $jobPayload['billed_amount'] = number_format(coolopz_calculate_billed_amount($jobForm['service_lines']), 2, '.', '');

            try {
                if ($action === 'update') {
                    coolopz_update_job($editJobId, $jobPayload);
                    header('Location: jobs.php?message=updated');
                    exit;
                }

                coolopz_create_job($jobPayload);
                header('Location: jobs.php?message=created');
                exit;
            } catch (PDOException $exception) {
                $errorMessage = str_contains($exception->getMessage(), 'Duplicate')
                    ? 'That ticket number already exists.'
                    : 'Unable to save the job right now.';
                $shouldOpenJobModal = true;
            }
        }
    }
}

if ($editJobId > 0 && $_SERVER['REQUEST_METHOD'] !== 'POST') {
    $editingJob = coolopz_find_job($editJobId);

    if ($editingJob === null) {
        $errorMessage = 'The selected job could not be found.';
        $editJobId = 0;
    } else {
        $shouldOpenJobModal = true;
        $reportUploadJobId = $editJobId;
        $jobForm = coolopz_build_job_form_from_record($editingJob, $servicePriceMap);
    }
}

if ($reportUploadJobId > 0) {
    $jobReportPhotoMap = coolopz_job_report_photo_map($reportUploadJobId);
}

$jobMetrics = coolopz_fetch_job_metrics();
$jobs = coolopz_fetch_jobs();

include __DIR__ . '/includes/head.php';
include __DIR__ . '/includes/sidebar.php';
?>
        <main class="portal-main">
<?php include __DIR__ . '/includes/topbar.php'; ?>
            <section class="hero-section">
                <span class="section-label">Jobs</span>
                <p class="hero-copy">Create, update, and close service jobs without leaving the operations board.</p>
            </section>
            <section class="row g-2 g-lg-3">
                <div class="col-md-4">
                    <div class="simple-panel stat-card">
                        <span class="stat-label">Open Tickets</span>
                        <strong class="stat-value"><?= htmlspecialchars((string) $jobMetrics['open_tickets'], ENT_QUOTES, 'UTF-8') ?></strong>
                        <p>All service jobs not yet closed.</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="simple-panel stat-card">
                        <span class="stat-label">On Site</span>
                        <strong class="stat-value"><?= htmlspecialchars((string) $jobMetrics['on_site'], ENT_QUOTES, 'UTF-8') ?></strong>
                        <p>Technicians currently working at client locations.</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="simple-panel stat-card">
                        <span class="stat-label">Awaiting Parts</span>
                        <strong class="stat-value"><?= htmlspecialchars((string) $jobMetrics['awaiting_parts'], ENT_QUOTES, 'UTF-8') ?></strong>
                        <p>Jobs paused until replacement parts arrive.</p>
                    </div>
                </div>
            </section>
            <section class="row g-3 mt-0">
                <div class="col-12">
                    <div class="simple-panel h-100">
                        <div class="panel-head mb-2">
                            <div>
                                <span class="section-label">Service board</span>
                                <h2 class="panel-title">Manage Jobs</h2>
                            </div>
                            <div class="jobs-actions">
                                <span class="subtle-note"><?= htmlspecialchars((string) count($jobs), ENT_QUOTES, 'UTF-8') ?> listed</span>
                                <button type="button" class="btn btn-portal-primary btn-sm" data-bs-toggle="modal" data-bs-target="#jobModal">Add Job</button>
                            </div>
                        </div>

<?php if ($errorMessage !== ''): ?>
                        <div class="login-alert mb-2" role="alert"><?= htmlspecialchars($errorMessage, ENT_QUOTES, 'UTF-8') ?></div>
<?php endif; ?>

<?php if ($successMessage !== ''): ?>
                        <div class="form-success mb-2" role="status"><?= htmlspecialchars($successMessage, ENT_QUOTES, 'UTF-8') ?></div>
<?php endif; ?>

                        <div class="table-responsive">
                            <table class="table portal-table align-middle mb-0">
                                <thead>
                                    <tr>
                                        <th>Ticket</th>
                                        <th>Client</th>
                                        <th>Service</th>
                                        <th>Technician</th>
                                        <th>Status</th>
                                        <th>Priority</th>
                                        <th>Billed</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
<?php foreach ($jobs as $job): ?>
<?php $clientUpdateUrl = coolopz_job_client_update_url((string) $job['client_update_token']); ?>
<?php $clientWhatsappUrl = coolopz_job_client_whatsapp_url($job); ?>
                                    <tr>
                                        <td><?= htmlspecialchars($job['ticket_number'], ENT_QUOTES, 'UTF-8') ?></td>
                                        <td>
                                            <strong class="d-block"><?= htmlspecialchars($job['customer_name'] !== '' ? $job['customer_name'] : 'Add later', ENT_QUOTES, 'UTF-8') ?></strong>
                                            <span class="subtle-note"><?= htmlspecialchars(($job['person_in_charge_name'] ?? '') !== '' ? $job['person_in_charge_name'] : 'Person In Charge pending', ENT_QUOTES, 'UTF-8') ?><?= ($job['person_in_charge_contact'] ?? '') !== '' ? ' | ' . htmlspecialchars($job['person_in_charge_contact'], ENT_QUOTES, 'UTF-8') : '' ?></span>
                                        </td>
                                        <td>
                                            <strong class="d-block"><?= htmlspecialchars($job['service_type'], ENT_QUOTES, 'UTF-8') ?></strong>
<?php if (($job['site_address'] ?? '') !== ''): ?>
                                            <span class="subtle-note d-block"><?= htmlspecialchars($job['site_address'], ENT_QUOTES, 'UTF-8') ?></span>
<?php else: ?>
                                            <span class="subtle-note d-block">No site address added</span>
<?php endif; ?>
<?php if (($job['google_maps_url'] ?? '') !== ''): ?>
                                            <a class="subtle-note" href="<?= htmlspecialchars($job['google_maps_url'], ENT_QUOTES, 'UTF-8') ?>" target="_blank" rel="noopener noreferrer">Open map</a>
<?php endif; ?>
                                        </td>
                                        <td>
                                            <strong class="d-block"><?= htmlspecialchars($job['technician_team'] !== '' ? $job['technician_team'] : 'Add later', ENT_QUOTES, 'UTF-8') ?></strong>
                                            <span class="subtle-note"><?= htmlspecialchars(($job['attending_technicians'] ?? '') !== '' ? $job['attending_technicians'] : 'No attending team yet', ENT_QUOTES, 'UTF-8') ?></span>
                                        </td>
                                        <td><span class="status-badge <?= coolopz_status_badge_class($job['status']) ?>"><?= htmlspecialchars($job['status'], ENT_QUOTES, 'UTF-8') ?></span></td>
                                        <td><?= htmlspecialchars($job['priority_level'], ENT_QUOTES, 'UTF-8') ?></td>
                                        <td><?= htmlspecialchars((float) $job['billed_amount'] > 0 ? 'RM' . number_format((float) $job['billed_amount'], 2) : 'Pending', ENT_QUOTES, 'UTF-8') ?></td>
                                        <td>
                                            <div class="jobs-actions">
                                                <a class="btn btn-portal-secondary btn-sm" href="jobs.php?edit=<?= htmlspecialchars((string) $job['id'], ENT_QUOTES, 'UTF-8') ?>">Edit</a>
                                                <a class="btn btn-outline-primary btn-sm" href="<?= htmlspecialchars($clientUpdateUrl, ENT_QUOTES, 'UTF-8') ?>" target="_blank" rel="noopener noreferrer">Client Form</a>
                                                <button type="button" class="btn btn-outline-secondary btn-sm" data-copy-client-link="<?= htmlspecialchars($clientUpdateUrl, ENT_QUOTES, 'UTF-8') ?>">Copy Link</button>
                                                <a class="btn btn-outline-success btn-sm" href="<?= htmlspecialchars($clientWhatsappUrl, ENT_QUOTES, 'UTF-8') ?>" target="_blank" rel="noopener noreferrer">WhatsApp</a>
                                                <form method="post" class="m-0" onsubmit="return confirm('Regenerate the client link for this job? The old link will stop working.');">
                                                    <input type="hidden" name="action" value="regenerate_client_link">
                                                    <input type="hidden" name="job_id" value="<?= htmlspecialchars((string) $job['id'], ENT_QUOTES, 'UTF-8') ?>">
                                                    <button type="submit" class="btn btn-outline-warning btn-sm">Regenerate</button>
                                                </form>
                                                <form method="post" class="m-0" onsubmit="return confirm('Delete this job?');">
                                                    <input type="hidden" name="action" value="delete">
                                                    <input type="hidden" name="job_id" value="<?= htmlspecialchars((string) $job['id'], ENT_QUOTES, 'UTF-8') ?>">
                                                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
<?php endforeach; ?>
<?php if ($jobs === []): ?>
                                    <tr>
                                        <td colspan="8" class="text-center text-muted py-4">No jobs available yet.</td>
                                    </tr>
<?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>

            <div class="modal fade" id="jobModal" tabindex="-1" aria-labelledby="jobModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <div>
                                <span class="section-label mb-2"><?= $editJobId > 0 ? 'Edit job' : 'Create job' ?></span>
                                <h2 class="panel-title" id="jobModalLabel"><?= $editJobId > 0 ? 'Update Job' : 'Add New Job' ?></h2>
                            </div>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
<?php if ($errorMessage !== ''): ?>
                            <div class="login-alert" role="alert"><?= htmlspecialchars($errorMessage, ENT_QUOTES, 'UTF-8') ?></div>
<?php endif; ?>

                            <form method="post" class="row g-2">
                                <input type="hidden" name="action" value="<?= $editJobId > 0 ? 'update' : 'create' ?>">
<?php if ($editJobId > 0): ?>
                                <input type="hidden" name="job_id" value="<?= htmlspecialchars((string) $editJobId, ENT_QUOTES, 'UTF-8') ?>">
<?php endif; ?>
                                <div class="col-md-6">
                                    <label class="form-label" for="ticket_number">Ticket Number</label>
                                    <input class="form-control" id="ticket_number" name="ticket_number" type="text" value="<?= htmlspecialchars($jobForm['ticket_number'], ENT_QUOTES, 'UTF-8') ?>" readonly>
                                    <div class="form-text"><?= $editJobId > 0 ? 'Ticket numbers stay fixed after creation.' : 'Ticket number is generated automatically when you create the job.' ?></div>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="customer_name">Customer</label>
                                    <select class="form-select" id="customer_name" name="customer_name">
                                        <option value="">Add customer later</option>
<?php foreach ($customerOptions as $customer): ?>
                                        <option value="<?= htmlspecialchars($customer['name'], ENT_QUOTES, 'UTF-8') ?>"<?= $jobForm['customer_name'] === $customer['name'] ? ' selected' : '' ?>><?= htmlspecialchars($customer['name'], ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
<?php if ($jobForm['customer_name'] !== '' && !in_array($jobForm['customer_name'], array_map(static fn (array $customer): string => $customer['name'], $customerOptions), true)): ?>
                                        <option value="<?= htmlspecialchars($jobForm['customer_name'], ENT_QUOTES, 'UTF-8') ?>" selected><?= htmlspecialchars($jobForm['customer_name'] . ' (existing customer)', ENT_QUOTES, 'UTF-8') ?></option>
<?php endif; ?>
                                    </select>
                                    <div class="form-text">You can create the job now and assign the customer later.</div>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="service_type">Service Type</label>
                                    <div class="d-flex gap-2 align-items-start">
                                        <select class="form-select" id="service_type_selector">
<?php if ($serviceTypes === []): ?>
                                            <option value="">No services available</option>
<?php else: ?>
                                            <option value="">Select service type</option>
<?php foreach ($serviceTypes as $serviceType): ?>
                                            <option value="<?= htmlspecialchars($serviceType, ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars($serviceType, ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
<?php endif; ?>
                                        </select>
                                        <button type="button" class="btn btn-portal-secondary" id="addServiceTypeButton">Add</button>
                                    </div>
                                    <div class="form-text">Manage the dropdown items from the Services page.</div>
                                </div>
                                <div class="col-12">
                                    <div class="table-responsive">
                                        <table class="table portal-table align-middle mb-0" id="jobServiceTypesTable">
                                            <thead>
                                                <tr>
                                                    <th>Service Type</th>
                                                    <th>Price</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
<?php foreach ($jobForm['service_lines'] as $serviceLine): ?>
                                                <tr data-service-type="<?= htmlspecialchars((string) $serviceLine['service_name'], ENT_QUOTES, 'UTF-8') ?>">
                                                    <td>
                                                        <?= htmlspecialchars((string) $serviceLine['service_name'], ENT_QUOTES, 'UTF-8') ?>
                                                        <input type="hidden" name="service_types[]" value="<?= htmlspecialchars((string) $serviceLine['service_name'], ENT_QUOTES, 'UTF-8') ?>">
                                                    </td>
                                                    <td>
                                                        <input class="form-control form-control-sm" name="service_prices[]" type="number" min="0" step="0.01" value="<?= htmlspecialchars(number_format((float) $serviceLine['line_price'], 2, '.', ''), ENT_QUOTES, 'UTF-8') ?>">
                                                    </td>
                                                    <td><button type="button" class="btn btn-outline-danger btn-sm" data-remove-service-type>Remove</button></td>
                                                </tr>
<?php endforeach; ?>
<?php if ($jobForm['service_lines'] === []): ?>
                                                <tr class="job-service-types-empty-row">
                                                    <td colspan="3" class="text-center text-muted py-3">No service types added yet.</td>
                                                </tr>
<?php endif; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="technician_team">Lead Technician</label>
                                    <select class="form-select" id="technician_team" name="technician_team">
                                        <option value="">Add technician later</option>
<?php foreach ($staffTechnicians as $staffUser): ?>
                                        <option value="<?= htmlspecialchars($staffUser['full_name'], ENT_QUOTES, 'UTF-8') ?>"<?= $jobForm['technician_team'] === $staffUser['full_name'] ? ' selected' : '' ?>><?= htmlspecialchars($staffUser['full_name'] . ' (' . $staffUser['role_name'] . ')', ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
<?php if ($jobForm['technician_team'] !== '' && !in_array($jobForm['technician_team'], $staffTechnicianNames, true)): ?>
                                        <option value="<?= htmlspecialchars($jobForm['technician_team'], ENT_QUOTES, 'UTF-8') ?>" selected><?= htmlspecialchars($jobForm['technician_team'] . ' (existing assignment)', ENT_QUOTES, 'UTF-8') ?></option>
<?php endif; ?>
                                    </select>
                                    <div class="form-text">You can assign the lead technician later.</div>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="attending_technicians">Technicians Attending</label>
                                    <select class="form-select" id="attending_technicians" name="attending_technicians[]" multiple size="5">
<?php foreach ($staffTechnicians as $staffUser): ?>
                                        <option value="<?= htmlspecialchars($staffUser['full_name'], ENT_QUOTES, 'UTF-8') ?>"<?= in_array($staffUser['full_name'], $jobForm['attending_technicians'], true) ? ' selected' : '' ?>><?= htmlspecialchars($staffUser['full_name'] . ' (' . $staffUser['role_name'] . ')', ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
<?php foreach (array_diff($jobForm['attending_technicians'], $staffTechnicianNames) as $existingTechnician): ?>
                                        <option value="<?= htmlspecialchars($existingTechnician, ENT_QUOTES, 'UTF-8') ?>" selected><?= htmlspecialchars($existingTechnician . ' (existing assignment)', ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
                                    </select>
                                    <div class="form-text">Select one or more technicians who will attend this job.</div>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="site_address">Site Address</label>
                                    <input class="form-control" id="site_address" name="site_address" type="text" value="<?= htmlspecialchars($jobForm['site_address'], ENT_QUOTES, 'UTF-8') ?>" placeholder="Optional">
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="google_maps_url">Google Maps Link</label>
                                    <input class="form-control" id="google_maps_url" name="google_maps_url" type="url" value="<?= htmlspecialchars($jobForm['google_maps_url'], ENT_QUOTES, 'UTF-8') ?>" placeholder="https://maps.google.com/...">
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="person_in_charge_name">Person In Charge Name</label>
                                    <input class="form-control" id="person_in_charge_name" name="person_in_charge_name" type="text" value="<?= htmlspecialchars($jobForm['person_in_charge_name'], ENT_QUOTES, 'UTF-8') ?>" placeholder="Optional">
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="person_in_charge_contact">Person In Charge Phone Number</label>
                                    <input class="form-control" id="person_in_charge_contact" name="person_in_charge_contact" type="tel" inputmode="tel" value="<?= htmlspecialchars($jobForm['person_in_charge_contact'], ENT_QUOTES, 'UTF-8') ?>" placeholder="Optional phone number">
                                </div>
                                <div class="col-12">
                                    <label class="form-label" for="client_update_link">Client Update Link</label>
<?php if ($jobForm['client_update_token'] !== ''): ?>
                                    <div class="input-group">
                                        <input class="form-control" id="client_update_link" type="text" value="<?= htmlspecialchars(coolopz_job_client_update_url($jobForm['client_update_token']), ENT_QUOTES, 'UTF-8') ?>" readonly>
                                        <button type="button" class="btn btn-portal-secondary" data-copy-target="client_update_link">Copy</button>
                                        <a class="btn btn-outline-success" href="<?= htmlspecialchars(coolopz_job_client_whatsapp_url([
                                            'ticket_number' => $jobForm['ticket_number'],
                                            'customer_name' => $jobForm['customer_name'],
                                            'client_update_token' => $jobForm['client_update_token'],
                                        ]), ENT_QUOTES, 'UTF-8') ?>" target="_blank" rel="noopener noreferrer">WhatsApp</a>
                                    </div>
                                    <div class="form-text">Send this unique link to the client so they can fill in the site details directly.</div>
<?php else: ?>
                                    <div class="form-text">The unique client link will be generated automatically after you create the job.</div>
<?php endif; ?>
                                    <input type="hidden" name="client_update_token" value="<?= htmlspecialchars($jobForm['client_update_token'], ENT_QUOTES, 'UTF-8') ?>">
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="billed_amount">Billed Amount</label>
                                    <input class="form-control" id="billed_amount" name="billed_amount" type="text" value="<?= htmlspecialchars((string) $jobForm['billed_amount'], ENT_QUOTES, 'UTF-8') ?>" readonly>
                                    <div class="form-text">Calculated automatically from the selected services.</div>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="status">Status</label>
                                    <select class="form-select" id="status" name="status">
<?php foreach ($statuses as $status): ?>
                                        <option value="<?= htmlspecialchars($status, ENT_QUOTES, 'UTF-8') ?>"<?= $jobForm['status'] === $status ? ' selected' : '' ?>><?= htmlspecialchars($status, ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="priority_level">Priority</label>
                                    <select class="form-select" id="priority_level" name="priority_level">
<?php foreach ($priorities as $priority): ?>
                                        <option value="<?= htmlspecialchars($priority, ENT_QUOTES, 'UTF-8') ?>"<?= $jobForm['priority_level'] === $priority ? ' selected' : '' ?>><?= htmlspecialchars($priority, ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="col-12">
                                    <label class="form-label" for="notes">Notes</label>
                                    <textarea class="form-control notes-field" id="notes" name="notes" rows="4"><?= htmlspecialchars($jobForm['notes'], ENT_QUOTES, 'UTF-8') ?></textarea>
                                </div>
                                <div class="col-12 jobs-form-actions">
                                    <button type="submit" class="btn btn-portal-primary"><?= $editJobId > 0 ? 'Save Changes' : 'Create Job' ?></button>
                                    <a class="btn btn-portal-secondary" href="jobs.php">Cancel</a>
                                </div>
                            </form>

<?php if ($reportUploadJobId > 0): ?>
                            <div class="border-top mt-3 pt-3">
                                <span class="section-label">Technician Report Photos</span>
                                <h3 class="panel-title fs-6">Upload Before and After Photos</h3>
                                <p class="subtle-note mb-3">These photos will appear on the customer update page for this job.</p>
                                <form method="post" enctype="multipart/form-data" class="row g-3">
                                    <input type="hidden" name="action" value="upload_report_photos">
                                    <input type="hidden" name="job_id" value="<?= htmlspecialchars((string) $reportUploadJobId, ENT_QUOTES, 'UTF-8') ?>">
<?php foreach ($jobForm['service_lines'] as $index => $serviceLine): ?>
<?php $serviceName = (string) $serviceLine['service_name']; ?>
<?php $servicePhotos = $jobReportPhotoMap['services'][$serviceName] ?? ['before' => null, 'after' => null]; ?>
                                    <input type="hidden" name="service_report_keys[<?= htmlspecialchars((string) $index, ENT_QUOTES, 'UTF-8') ?>]" value="<?= htmlspecialchars($serviceName, ENT_QUOTES, 'UTF-8') ?>">
                                    <div class="col-12">
                                        <div class="simple-panel">
                                            <strong class="d-block mb-2"><?= htmlspecialchars($serviceName, ENT_QUOTES, 'UTF-8') ?></strong>
                                            <div class="row g-3">
                                                <div class="col-md-6">
                                                    <label class="form-label" for="service_before_<?= htmlspecialchars((string) $index, ENT_QUOTES, 'UTF-8') ?>">Before Photo</label>
                                                    <input class="form-control" id="service_before_<?= htmlspecialchars((string) $index, ENT_QUOTES, 'UTF-8') ?>" name="service_before[<?= htmlspecialchars((string) $index, ENT_QUOTES, 'UTF-8') ?>]" type="file" accept="image/jpeg,image/png,image/webp">
<?php if (($servicePhotos['before']['file_path'] ?? '') !== ''): ?>
                                                    <a class="d-inline-block mt-2" href="<?= htmlspecialchars((string) $servicePhotos['before']['file_path'], ENT_QUOTES, 'UTF-8') ?>" target="_blank" rel="noopener noreferrer">
                                                        <img class="img-fluid rounded border" src="<?= htmlspecialchars((string) $servicePhotos['before']['file_path'], ENT_QUOTES, 'UTF-8') ?>" alt="<?= htmlspecialchars($serviceName . ' before photo', ENT_QUOTES, 'UTF-8') ?>" style="max-height: 160px; object-fit: cover;">
                                                    </a>
                                                    <div class="form-text">Uploaded by <?= htmlspecialchars((string) ($servicePhotos['before']['uploaded_by_name'] ?? 'Technician'), ENT_QUOTES, 'UTF-8') ?></div>
<?php endif; ?>
                                                </div>
                                                <div class="col-md-6">
                                                    <label class="form-label" for="service_after_<?= htmlspecialchars((string) $index, ENT_QUOTES, 'UTF-8') ?>">After Photo</label>
                                                    <input class="form-control" id="service_after_<?= htmlspecialchars((string) $index, ENT_QUOTES, 'UTF-8') ?>" name="service_after[<?= htmlspecialchars((string) $index, ENT_QUOTES, 'UTF-8') ?>]" type="file" accept="image/jpeg,image/png,image/webp">
<?php if (($servicePhotos['after']['file_path'] ?? '') !== ''): ?>
                                                    <a class="d-inline-block mt-2" href="<?= htmlspecialchars((string) $servicePhotos['after']['file_path'], ENT_QUOTES, 'UTF-8') ?>" target="_blank" rel="noopener noreferrer">
                                                        <img class="img-fluid rounded border" src="<?= htmlspecialchars((string) $servicePhotos['after']['file_path'], ENT_QUOTES, 'UTF-8') ?>" alt="<?= htmlspecialchars($serviceName . ' after photo', ENT_QUOTES, 'UTF-8') ?>" style="max-height: 160px; object-fit: cover;">
                                                    </a>
                                                    <div class="form-text">Uploaded by <?= htmlspecialchars((string) ($servicePhotos['after']['uploaded_by_name'] ?? 'Technician'), ENT_QUOTES, 'UTF-8') ?></div>
<?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
<?php endforeach; ?>
                                    <div class="col-12">
                                        <div class="simple-panel">
                                            <strong class="d-block mb-2">Gas Refill Meter Report</strong>
                                            <div class="row g-3">
                                                <div class="col-md-6">
                                                    <label class="form-label" for="gas_meter_before">Meter Before</label>
                                                    <input class="form-control" id="gas_meter_before" name="gas_meter_before" type="file" accept="image/jpeg,image/png,image/webp">
<?php if (($jobReportPhotoMap['gas_meter']['before']['file_path'] ?? '') !== ''): ?>
                                                    <a class="d-inline-block mt-2" href="<?= htmlspecialchars((string) $jobReportPhotoMap['gas_meter']['before']['file_path'], ENT_QUOTES, 'UTF-8') ?>" target="_blank" rel="noopener noreferrer">
                                                        <img class="img-fluid rounded border" src="<?= htmlspecialchars((string) $jobReportPhotoMap['gas_meter']['before']['file_path'], ENT_QUOTES, 'UTF-8') ?>" alt="Gas meter before photo" style="max-height: 160px; object-fit: cover;">
                                                    </a>
<?php endif; ?>
                                                </div>
                                                <div class="col-md-6">
                                                    <label class="form-label" for="gas_meter_after">Meter After</label>
                                                    <input class="form-control" id="gas_meter_after" name="gas_meter_after" type="file" accept="image/jpeg,image/png,image/webp">
<?php if (($jobReportPhotoMap['gas_meter']['after']['file_path'] ?? '') !== ''): ?>
                                                    <a class="d-inline-block mt-2" href="<?= htmlspecialchars((string) $jobReportPhotoMap['gas_meter']['after']['file_path'], ENT_QUOTES, 'UTF-8') ?>" target="_blank" rel="noopener noreferrer">
                                                        <img class="img-fluid rounded border" src="<?= htmlspecialchars((string) $jobReportPhotoMap['gas_meter']['after']['file_path'], ENT_QUOTES, 'UTF-8') ?>" alt="Gas meter after photo" style="max-height: 160px; object-fit: cover;">
                                                    </a>
<?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 jobs-form-actions">
                                        <button type="submit" class="btn btn-portal-primary">Upload Report Photos</button>
                                    </div>
                                </form>
                            </div>
<?php elseif ($editJobId === 0): ?>
                            <div class="form-text mt-3">Save the job first, then upload service report and gas refill meter photos.</div>
<?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>

            <section class="row g-3 mt-0">
                <div class="col-12">
                    <div class="simple-panel h-100">
                        <div class="panel-head mb-2">
                            <div>
                                <span class="section-label">Service list</span>
                                <h2 class="panel-title">Available Services</h2>
                            </div>
                            <span class="subtle-note"><?= htmlspecialchars((string) count($services), ENT_QUOTES, 'UTF-8') ?> added</span>
                        </div>

                        <div class="table-responsive">
                            <table class="table portal-table align-middle mb-0">
                                <thead>
                                    <tr>
                                        <th>Service</th>
                                        <th>Default Price</th>
                                        <th>Notes</th>
                                    </tr>
                                </thead>
                                <tbody>
<?php foreach ($services as $service): ?>
                                    <tr>
                                        <td><?= htmlspecialchars($service['name'], ENT_QUOTES, 'UTF-8') ?></td>
                                        <td><?= htmlspecialchars((float) $service['default_price'] > 0 ? 'RM' . number_format((float) $service['default_price'], 2) : '-', ENT_QUOTES, 'UTF-8') ?></td>
                                        <td><?= htmlspecialchars($service['notes'] !== '' ? $service['notes'] : 'No notes added.', ENT_QUOTES, 'UTF-8') ?></td>
                                    </tr>
<?php endforeach; ?>
<?php if ($services === []): ?>
                                    <tr>
                                        <td colspan="3" class="text-center text-muted py-4">No services available yet.</td>
                                    </tr>
<?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>
        </main>
<?php if ($shouldOpenJobModal): ?>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var modalElement = document.getElementById('jobModal');
    if (!modalElement) {
        return;
    }

    var jobModal = new bootstrap.Modal(modalElement);
    jobModal.show();
});
</script>
<?php endif; ?>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var addButton = document.getElementById('addServiceTypeButton');
    var selector = document.getElementById('service_type_selector');
    var table = document.getElementById('jobServiceTypesTable');
    var billedAmountInput = document.getElementById('billed_amount');
    var servicePriceMap = <?= json_encode($servicePriceMap, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP) ?>;

    if (!addButton || !selector || !table || !billedAmountInput) {
        return;
    }

    var tableBody = table.querySelector('tbody');

    function updateBilledAmount() {
        var selectedInputs = tableBody.querySelectorAll('input[name="service_types[]"]');
        var total = 0;

        selectedInputs.forEach(function (input) {
            var row = input.closest('tr');
            if (!row) {
                return;
            }

            var priceInput = row.querySelector('input[name="service_prices[]"]');
            total += Number(priceInput ? priceInput.value : 0);
        });

        billedAmountInput.value = total.toFixed(2);
    }

    function removeEmptyRow() {
        var emptyRow = tableBody.querySelector('.job-service-types-empty-row');
        if (emptyRow) {
            emptyRow.remove();
        }
    }

    function ensureEmptyRow() {
        if (tableBody.querySelector('tr') !== null) {
            return;
        }

        var row = document.createElement('tr');
        row.className = 'job-service-types-empty-row';
        row.innerHTML = '<td colspan="3" class="text-center text-muted py-3">No service types added yet.</td>';
        tableBody.appendChild(row);
    }

    function addServiceTypeRow(serviceType) {
        if (!serviceType || tableBody.querySelector('tr[data-service-type="' + CSS.escape(serviceType) + '"]')) {
            return;
        }

        removeEmptyRow();

        var row = document.createElement('tr');
        row.setAttribute('data-service-type', serviceType);
        row.innerHTML = '<td>'
            + serviceType
            + '<input type="hidden" name="service_types[]" value="' + serviceType.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;') + '"></td>'
            + '<td><input class="form-control form-control-sm" name="service_prices[]" type="number" min="0" step="0.01" value="' + Number(servicePriceMap[serviceType] || 0).toFixed(2) + '"></td>'
            + '<td><button type="button" class="btn btn-outline-danger btn-sm" data-remove-service-type>Remove</button></td>';
        tableBody.appendChild(row);
        updateBilledAmount();
    }

    addButton.addEventListener('click', function () {
        addServiceTypeRow(selector.value);
        selector.value = '';
    });

    tableBody.addEventListener('click', function (event) {
        var target = event.target;
        if (!(target instanceof HTMLElement) || !target.hasAttribute('data-remove-service-type')) {
            return;
        }

        var row = target.closest('tr');
        if (row) {
            row.remove();
        }

        ensureEmptyRow();
        updateBilledAmount();
    });

    tableBody.addEventListener('input', function (event) {
        var target = event.target;
        if (!(target instanceof HTMLInputElement) || target.name !== 'service_prices[]') {
            return;
        }

        updateBilledAmount();
    });

    updateBilledAmount();
});

document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('[data-copy-client-link]').forEach(function (button) {
        button.addEventListener('click', function () {
            var link = button.getAttribute('data-copy-client-link') || '';
            if (link === '' || !navigator.clipboard) {
                return;
            }

            navigator.clipboard.writeText(link);
        });
    });

    document.querySelectorAll('[data-copy-target]').forEach(function (button) {
        button.addEventListener('click', function () {
            var targetId = button.getAttribute('data-copy-target') || '';
            var input = document.getElementById(targetId);
            if (!(input instanceof HTMLInputElement) || !navigator.clipboard) {
                return;
            }

            navigator.clipboard.writeText(input.value);
        });
    });

    var picPhoneInput = document.getElementById('person_in_charge_contact');

    if (picPhoneInput instanceof HTMLInputElement) {
        var normalizePhone = function () {
            picPhoneInput.value = picPhoneInput.value.replace(/\D+/g, '');
        };

        picPhoneInput.addEventListener('input', normalizePhone);
        picPhoneInput.addEventListener('paste', function () {
            setTimeout(normalizePhone, 0);
        });

        normalizePhone();
    }
});
</script>
<?php include __DIR__ . '/includes/footer.php'; ?>