<?php
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/data.php';

coolopz_require_login();

$currentUser = coolopz_current_user();
$pageTitle = 'CoolOpz Portal | Jobs';
$activePage = 'jobs';
$currentUserName = $currentUser['name'] ?? 'Admin User';
$currentUserRole = $currentUser['role'] ?? 'Operations Admin';
$userInitials = coolopz_user_initials($currentUserName);

$serviceTypes = coolopz_job_service_types();
$statuses = coolopz_job_statuses();
$priorities = coolopz_job_priorities();
$customerOptions = coolopz_fetch_customer_options();
$staffTechnicians = coolopz_fetch_assignable_staff();

$errorMessage = '';
$messageKey = (string) ($_GET['message'] ?? '');
$successMessage = match ($messageKey) {
    'created' => 'Job created successfully.',
    'updated' => 'Job updated successfully.',
    'deleted' => 'Job deleted successfully.',
    default => '',
};
$shouldOpenJobModal = false;
$autoGeneratedTicketNumber = coolopz_generate_job_ticket_number();

$jobForm = [
    'ticket_number' => $autoGeneratedTicketNumber,
    'customer_name' => '',
    'service_type' => 'Maintenance',
    'technician_team' => '',
    'zone' => '',
    'status' => 'Queued',
    'priority_level' => 'Medium',
    'billed_amount' => '',
    'notes' => '',
];

$editJobId = isset($_GET['edit']) ? (int) $_GET['edit'] : 0;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = (string) ($_POST['action'] ?? 'create');

    if ($action === 'delete') {
        $deleteJobId = (int) ($_POST['job_id'] ?? 0);

        if ($deleteJobId < 1 || coolopz_find_job($deleteJobId) === null) {
            $errorMessage = 'The selected job could not be found.';
            $shouldOpenJobModal = false;
        } else {
            coolopz_delete_job($deleteJobId);
            header('Location: jobs.php?message=deleted');
            exit;
        }
    } else {
        $editJobId = $action === 'update' ? (int) ($_POST['job_id'] ?? 0) : 0;
        $existingJob = $action === 'update' && $editJobId > 0 ? coolopz_find_job($editJobId) : null;
        $jobForm = [
            'ticket_number' => $action === 'update' && $existingJob !== null ? $existingJob['ticket_number'] : $autoGeneratedTicketNumber,
            'customer_name' => trim((string) ($_POST['customer_name'] ?? '')),
            'service_type' => trim((string) ($_POST['service_type'] ?? 'Maintenance')),
            'technician_team' => trim((string) ($_POST['technician_team'] ?? '')),
            'zone' => trim((string) ($_POST['zone'] ?? '')),
            'status' => trim((string) ($_POST['status'] ?? 'Queued')),
            'priority_level' => trim((string) ($_POST['priority_level'] ?? 'Medium')),
            'billed_amount' => trim((string) ($_POST['billed_amount'] ?? '')),
            'notes' => trim((string) ($_POST['notes'] ?? '')),
        ];
        $allowedCustomers = array_map(static fn (array $customer): string => $customer['name'], $customerOptions);
        $allowedTechnicians = array_map(static fn (array $staffUser): string => $staffUser['full_name'], $staffTechnicians);

        if ($action === 'update' && $existingJob !== null && $existingJob['customer_name'] !== '') {
            $allowedCustomers[] = $existingJob['customer_name'];
        }
        $allowedCustomers = array_values(array_unique($allowedCustomers));

        if ($action === 'update' && $existingJob !== null && $existingJob['technician_team'] !== '') {
            $allowedTechnicians[] = $existingJob['technician_team'];
        }
        $allowedTechnicians = array_values(array_unique($allowedTechnicians));

        if (
            $jobForm['customer_name'] === ''
            || $jobForm['technician_team'] === ''
        ) {
            $errorMessage = 'Customer and technician are required.';
            $shouldOpenJobModal = true;
        } elseif (!in_array($jobForm['customer_name'], $allowedCustomers, true)) {
            $errorMessage = 'Select a customer from the customer list.';
            $shouldOpenJobModal = true;
        } elseif (!in_array($jobForm['service_type'], $serviceTypes, true)) {
            $errorMessage = 'Select a valid service type.';
            $shouldOpenJobModal = true;
        } elseif (!in_array($jobForm['technician_team'], $allowedTechnicians, true)) {
            $errorMessage = 'Select a technician from the staff list.';
            $shouldOpenJobModal = true;
        } elseif (!in_array($jobForm['status'], $statuses, true)) {
            $errorMessage = 'Select a valid job status.';
            $shouldOpenJobModal = true;
        } elseif (!in_array($jobForm['priority_level'], $priorities, true)) {
            $errorMessage = 'Select a valid priority level.';
            $shouldOpenJobModal = true;
        } elseif ($jobForm['billed_amount'] !== '' && (!is_numeric($jobForm['billed_amount']) || (float) $jobForm['billed_amount'] < 0)) {
            $errorMessage = 'Billed amount must be a valid positive number.';
            $shouldOpenJobModal = true;
        } elseif ($action === 'update' && ($editJobId < 1 || $existingJob === null)) {
            $errorMessage = 'The job you are trying to update no longer exists.';
            $shouldOpenJobModal = true;
        } else {
            $jobPayload = $jobForm;
            $jobPayload['billed_amount'] = number_format((float) ($jobForm['billed_amount'] !== '' ? $jobForm['billed_amount'] : '0'), 2, '.', '');

            try {
                if ($action === 'update') {
                    coolopz_update_job($editJobId, $jobPayload);
                    header('Location: jobs.php?message=updated');
                    exit;
                }

                coolopz_create_job($jobPayload);
                header('Location: jobs.php?message=created');
                exit;
            } catch (PDOException $exception) {
                $errorMessage = str_contains($exception->getMessage(), 'Duplicate')
                    ? 'That ticket number already exists.'
                    : 'Unable to save the job right now.';
                $shouldOpenJobModal = true;
            }
        }
    }
}

if ($editJobId > 0 && $_SERVER['REQUEST_METHOD'] !== 'POST') {
    $editingJob = coolopz_find_job($editJobId);

    if ($editingJob === null) {
        $errorMessage = 'The selected job could not be found.';
        $editJobId = 0;
    } else {
        $shouldOpenJobModal = true;
        $jobForm = [
            'ticket_number' => $editingJob['ticket_number'],
            'customer_name' => $editingJob['customer_name'],
            'service_type' => $editingJob['service_type'],
            'technician_team' => $editingJob['technician_team'],
            'zone' => $editingJob['zone'],
            'status' => $editingJob['status'],
            'priority_level' => $editingJob['priority_level'],
            'billed_amount' => (float) $editingJob['billed_amount'] > 0 ? number_format((float) $editingJob['billed_amount'], 2, '.', '') : '',
            'notes' => $editingJob['notes'],
        ];
    }
}

$jobMetrics = coolopz_fetch_job_metrics();
$jobs = coolopz_fetch_jobs();

include __DIR__ . '/includes/head.php';
include __DIR__ . '/includes/sidebar.php';
?>
        <main class="portal-main">
<?php include __DIR__ . '/includes/topbar.php'; ?>
            <section class="hero-section">
                <span class="section-label">Jobs</span>
                <p class="hero-copy">Create, update, and close service jobs without leaving the operations board.</p>
            </section>
            <section class="row g-2 g-lg-3">
                <div class="col-md-4">
                    <div class="simple-panel stat-card">
                        <span class="stat-label">Open Tickets</span>
                        <strong class="stat-value"><?= htmlspecialchars((string) $jobMetrics['open_tickets'], ENT_QUOTES, 'UTF-8') ?></strong>
                        <p>All service jobs not yet closed.</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="simple-panel stat-card">
                        <span class="stat-label">On Site</span>
                        <strong class="stat-value"><?= htmlspecialchars((string) $jobMetrics['on_site'], ENT_QUOTES, 'UTF-8') ?></strong>
                        <p>Technicians currently working at client locations.</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="simple-panel stat-card">
                        <span class="stat-label">Awaiting Parts</span>
                        <strong class="stat-value"><?= htmlspecialchars((string) $jobMetrics['awaiting_parts'], ENT_QUOTES, 'UTF-8') ?></strong>
                        <p>Jobs paused until replacement parts arrive.</p>
                    </div>
                </div>
            </section>
            <section class="row g-3 mt-0">
                <div class="col-12">
                    <div class="simple-panel h-100">
                        <div class="panel-head mb-2">
                            <div>
                                <span class="section-label">Service board</span>
                                <h2 class="panel-title">Manage Jobs</h2>
                            </div>
                            <div class="jobs-actions">
                                <span class="subtle-note"><?= htmlspecialchars((string) count($jobs), ENT_QUOTES, 'UTF-8') ?> listed</span>
                                <button type="button" class="btn btn-portal-primary btn-sm" data-bs-toggle="modal" data-bs-target="#jobModal">Add Job</button>
                            </div>
                        </div>

<?php if ($errorMessage !== ''): ?>
                        <div class="login-alert mb-2" role="alert"><?= htmlspecialchars($errorMessage, ENT_QUOTES, 'UTF-8') ?></div>
<?php endif; ?>

<?php if ($successMessage !== ''): ?>
                        <div class="form-success mb-2" role="status"><?= htmlspecialchars($successMessage, ENT_QUOTES, 'UTF-8') ?></div>
<?php endif; ?>

                        <div class="table-responsive">
                            <table class="table portal-table align-middle mb-0">
                                <thead>
                                    <tr>
                                        <th>Ticket</th>
                                        <th>Client</th>
                                        <th>Service</th>
                                        <th>Technician</th>
                                        <th>Status</th>
                                        <th>Priority</th>
                                        <th>Billed</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
<?php foreach ($jobs as $job): ?>
                                    <tr>
                                        <td><?= htmlspecialchars($job['ticket_number'], ENT_QUOTES, 'UTF-8') ?></td>
                                        <td><?= htmlspecialchars($job['customer_name'], ENT_QUOTES, 'UTF-8') ?></td>
                                        <td>
                                            <strong class="d-block"><?= htmlspecialchars($job['service_type'], ENT_QUOTES, 'UTF-8') ?></strong>
                                            <span class="subtle-note"><?= htmlspecialchars($job['zone'] !== '' ? $job['zone'] : 'No zone assigned', ENT_QUOTES, 'UTF-8') ?></span>
                                        </td>
                                        <td><?= htmlspecialchars($job['technician_team'], ENT_QUOTES, 'UTF-8') ?></td>
                                        <td><span class="status-badge <?= coolopz_status_badge_class($job['status']) ?>"><?= htmlspecialchars($job['status'], ENT_QUOTES, 'UTF-8') ?></span></td>
                                        <td><?= htmlspecialchars($job['priority_level'], ENT_QUOTES, 'UTF-8') ?></td>
                                        <td><?= htmlspecialchars((float) $job['billed_amount'] > 0 ? 'RM' . number_format((float) $job['billed_amount'], 2) : 'Pending', ENT_QUOTES, 'UTF-8') ?></td>
                                        <td>
                                            <div class="jobs-actions">
                                                <a class="btn btn-portal-secondary btn-sm" href="jobs.php?edit=<?= htmlspecialchars((string) $job['id'], ENT_QUOTES, 'UTF-8') ?>">Edit</a>
                                                <form method="post" class="m-0" onsubmit="return confirm('Delete this job?');">
                                                    <input type="hidden" name="action" value="delete">
                                                    <input type="hidden" name="job_id" value="<?= htmlspecialchars((string) $job['id'], ENT_QUOTES, 'UTF-8') ?>">
                                                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
<?php endforeach; ?>
<?php if ($jobs === []): ?>
                                    <tr>
                                        <td colspan="8" class="text-center text-muted py-4">No jobs available yet.</td>
                                    </tr>
<?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>

            <div class="modal fade" id="jobModal" tabindex="-1" aria-labelledby="jobModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <div>
                                <span class="section-label mb-2"><?= $editJobId > 0 ? 'Edit job' : 'Create job' ?></span>
                                <h2 class="panel-title" id="jobModalLabel"><?= $editJobId > 0 ? 'Update Job' : 'Add New Job' ?></h2>
                            </div>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
<?php if ($errorMessage !== ''): ?>
                            <div class="login-alert" role="alert"><?= htmlspecialchars($errorMessage, ENT_QUOTES, 'UTF-8') ?></div>
<?php endif; ?>

                            <form method="post" class="row g-2">
                                <input type="hidden" name="action" value="<?= $editJobId > 0 ? 'update' : 'create' ?>">
<?php if ($editJobId > 0): ?>
                                <input type="hidden" name="job_id" value="<?= htmlspecialchars((string) $editJobId, ENT_QUOTES, 'UTF-8') ?>">
<?php endif; ?>
                                <div class="col-md-6">
                                    <label class="form-label" for="ticket_number">Ticket Number</label>
                                    <input class="form-control" id="ticket_number" name="ticket_number" type="text" value="<?= htmlspecialchars($jobForm['ticket_number'], ENT_QUOTES, 'UTF-8') ?>" readonly>
                                    <div class="form-text"><?= $editJobId > 0 ? 'Ticket numbers stay fixed after creation.' : 'Ticket number is generated automatically when you create the job.' ?></div>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="customer_name">Customer</label>
                                    <select class="form-select" id="customer_name" name="customer_name" required>
                                        <option value="">Select customer</option>
<?php foreach ($customerOptions as $customer): ?>
                                        <option value="<?= htmlspecialchars($customer['name'], ENT_QUOTES, 'UTF-8') ?>"<?= $jobForm['customer_name'] === $customer['name'] ? ' selected' : '' ?>><?= htmlspecialchars($customer['name'], ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
<?php if ($jobForm['customer_name'] !== '' && !in_array($jobForm['customer_name'], array_map(static fn (array $customer): string => $customer['name'], $customerOptions), true)): ?>
                                        <option value="<?= htmlspecialchars($jobForm['customer_name'], ENT_QUOTES, 'UTF-8') ?>" selected><?= htmlspecialchars($jobForm['customer_name'] . ' (existing customer)', ENT_QUOTES, 'UTF-8') ?></option>
<?php endif; ?>
                                    </select>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="service_type">Service Type</label>
                                    <select class="form-select" id="service_type" name="service_type">
<?php foreach ($serviceTypes as $serviceType): ?>
                                        <option value="<?= htmlspecialchars($serviceType, ENT_QUOTES, 'UTF-8') ?>"<?= $jobForm['service_type'] === $serviceType ? ' selected' : '' ?>><?= htmlspecialchars($serviceType, ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="technician_team">Technician</label>
                                    <select class="form-select" id="technician_team" name="technician_team" required>
                                        <option value="">Select technician</option>
<?php foreach ($staffTechnicians as $staffUser): ?>
                                        <option value="<?= htmlspecialchars($staffUser['full_name'], ENT_QUOTES, 'UTF-8') ?>"<?= $jobForm['technician_team'] === $staffUser['full_name'] ? ' selected' : '' ?>><?= htmlspecialchars($staffUser['full_name'] . ' (' . $staffUser['role_name'] . ')', ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
<?php if ($jobForm['technician_team'] !== '' && !in_array($jobForm['technician_team'], array_map(static fn (array $staffUser): string => $staffUser['full_name'], $staffTechnicians), true)): ?>
                                        <option value="<?= htmlspecialchars($jobForm['technician_team'], ENT_QUOTES, 'UTF-8') ?>" selected><?= htmlspecialchars($jobForm['technician_team'] . ' (existing assignment)', ENT_QUOTES, 'UTF-8') ?></option>
<?php endif; ?>
                                    </select>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="zone">Zone</label>
                                    <input class="form-control" id="zone" name="zone" type="text" value="<?= htmlspecialchars($jobForm['zone'], ENT_QUOTES, 'UTF-8') ?>" placeholder="Optional">
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="billed_amount">Billed Amount</label>
                                    <input class="form-control" id="billed_amount" name="billed_amount" type="number" min="0" step="0.01" value="<?= htmlspecialchars((string) $jobForm['billed_amount'], ENT_QUOTES, 'UTF-8') ?>" placeholder="Add later if not billed yet">
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="status">Status</label>
                                    <select class="form-select" id="status" name="status">
<?php foreach ($statuses as $status): ?>
                                        <option value="<?= htmlspecialchars($status, ENT_QUOTES, 'UTF-8') ?>"<?= $jobForm['status'] === $status ? ' selected' : '' ?>><?= htmlspecialchars($status, ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="priority_level">Priority</label>
                                    <select class="form-select" id="priority_level" name="priority_level">
<?php foreach ($priorities as $priority): ?>
                                        <option value="<?= htmlspecialchars($priority, ENT_QUOTES, 'UTF-8') ?>"<?= $jobForm['priority_level'] === $priority ? ' selected' : '' ?>><?= htmlspecialchars($priority, ENT_QUOTES, 'UTF-8') ?></option>
<?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="col-12">
                                    <label class="form-label" for="notes">Notes</label>
                                    <textarea class="form-control notes-field" id="notes" name="notes" rows="4"><?= htmlspecialchars($jobForm['notes'], ENT_QUOTES, 'UTF-8') ?></textarea>
                                </div>
                                <div class="col-12 jobs-form-actions">
                                    <button type="submit" class="btn btn-portal-primary"><?= $editJobId > 0 ? 'Save Changes' : 'Create Job' ?></button>
                                    <a class="btn btn-portal-secondary" href="jobs.php">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
<?php if ($shouldOpenJobModal): ?>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var modalElement = document.getElementById('jobModal');
    if (!modalElement) {
        return;
    }

    var jobModal = new bootstrap.Modal(modalElement);
    jobModal.show();
});
</script>
<?php endif; ?>
<?php include __DIR__ . '/includes/footer.php'; ?>